pool:
  vmImage: 'ubuntu-latest'

trigger: none

variables:
  - template: ../actions/variables.yml

stages:
- stage: 'Build'
  displayName: 'Version, Infra Plan, Build & Test'
  
  jobs:
  - job: 'Version'
    displayName: 'Version'
    steps:
    - template: ../actions/version.yml
      parameters:
        version: $(version)

  - job: 'Infra'
    displayName: 'Infra Plan'
    dependsOn: ["Version"]
    steps:
    - template: ../actions/app-config.yml
      parameters:
        serviceConnection: $(serviceConnection)
        appConfigName: $(appConfigName)
        environment: $(environment)

    - template: ../actions/tf-plan.yml
      parameters:
        serviceConnection: $(serviceConnection)
        subscriptionId: $(Devops:SubscriptionId)
        storageAccountName: $(Devops:StorageName)
        containerName: $(Devops:ContainerName)
        workingDirectory: '$(Build.SourcesDirectory)/build/infra'
        environment: $(environment)
        db_username: $(Devops:DB:Username)
        db_password: $(Devops:DB:Password)
        keyVaultName: $(Devops:KeyVault)
        appConfigName: $(appConfigName)

  - job: 'Build'
    displayName: 'Build & Test'
    dependsOn: ["Version"]
    steps:
    - template: ../actions/build.yml
      parameters:
        workingDirectory: '$(Build.SourcesDirectory)/src'
        test: true
        artifact: false