parameters:
  - name: serviceConnection
  - name: appConfigName
  - name: environment
  
steps:
- task: AzureAppConfiguration@3
  displayName: 'Link App Configuration'
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    ConfigstoreName: ${{ parameters.appConfigName }}
    KeyFilter: '*'
    label: ${{ parameters.environment }}

- task: Bash@3
  displayName: 'List all environment variables'
  inputs:
    targetType: 'inline'
    script: 'env | sort'