name: deploy
description: Template - Deploy

inputs:
  function_app_name:
    required: true
  package_path:
    required: true

runs:
  using: "composite"
  steps:

  - name: 'Deploy to Azure Function App'
    uses: Azure/functions-action@v1
    with:
      app-name: ${{ inputs.function_app_name }}
      package: ${{ inputs.package_path }}
