name: Release to Azure Function App

inputs:
  environment:
    required: true
    type: string
  function_app_name:
    required: true
    type: string
  package_path:
    required: true
    type: string

jobs:
  release:
    name: 'Deploy Function App'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v3

    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Function App'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ inputs.function_app_name }}
        package: ${{ inputs.package_path }}
        publish-profile: ${{ secrets.FUNCTION_APP_PUBLISH_PROFILE }}
