name: deploy
description: Template - Deploy

inputs:
  azure_credentials:
    required: true
  function_app_name:
    required: true
  package_path:
    required: true

runs:
  using: "composite"
  steps:
  - name: 'Azure Login'
    uses: azure/login@v1
    with:
      creds: ${{ secrets.AZURE_CREDENTIALS }}

  - name: 'Deploy to Azure Function App'
    uses: Azure/functions-action@v1
    with:
      app-name: ${{ inputs.function_app_name }}
      package: ${{ inputs.package_path }}
