name: PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - release/*
      - hotfix/*

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: Dev
      b2c_authority: ${{ env.B2C_AUTHORITY }}
      b2c_issuer: ${{ env.B2C_ISSUER }}
      b2c_client_id: ${{ env.B2C_CLIENT_ID }}
      apply_changes: false

  build:
    needs: terraform
    uses: ./.github/workflows/build.yml
    with:
      environment: Dev
