name: PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - release/*
      - hotfix/*

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    environment: Dev
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: ./.github/templates/setup
        with:
          environment: Dev
          azure_creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: ./.github/templates/terraform
        with:
          environment: Dev
          b2c_authority: ${{ vars.B2C_AUTHORITY }}
          b2c_issuer: ${{ vars.B2C_ISSUER }}
          b2c_client_id: ${{ vars.B2C_CLIENT_ID }}
          apply_changes: false

      - uses: ./.github/templates/build