name: Release (Dev)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy
    environment: Dev
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: ./.github/templates/setup
        with:
          environment: Dev
          azure_creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: ./.github/templates/terraform
        with:
          environment: Dev
          b2c_authority: ${{ vars.B2C_AUTHORITY }}
          b2c_issuer: ${{ vars.B2C_ISSUER }}
          b2c_client_id: ${{ vars.B2C_CLIENT_ID }}
          apply_changes: true

      - uses: ./.github/templates/build

      - uses: ./.github/templates/deploy
        with:
          function_app_name: ${{ env.FUNCTION_APP_NAME }}
          package_path: ./publish/functionapp.zip
