name: Release to live

on:
  workflow_dispatch:

jobs:
  terraform:
    uses: ./.github/templates/terraform
    with:
      environment: Live
      b2c_authority: ${{ env.B2C_AUTHORITY }}
      b2c_issuer: ${{ env.B2C_ISSUER }}
      b2c_client_id: ${{ env.B2C_CLIENT_ID }}
      apply_changes: true

  build:
    needs: terraform
    uses: ./.github/templates/build
    with:
      environment: Live

  release:
    needs: [build]
    uses: ./.github/templates/deploy
    with:
      environment: Live
      function_app_name: ${{ needs.terraform.outputs.function_app_name }}
      package_path: ${{ needs.build.outputs.package_path }}
