name: Release (Live)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy
    environment: Live
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: ./.github/templates/terraform
        with:
          environment: Live
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          b2c_authority: ${{ env.B2C_AUTHORITY }}
          b2c_issuer: ${{ env.B2C_ISSUER }}
          b2c_client_id: ${{ env.B2C_CLIENT_ID }}
          apply_changes: true

      - uses: ./.github/templates/build

      - uses: ./.github/templates/deploy
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          function_app_name: ${{ env.TERRAFORM_FUNCTION_APP_NAME }}
          package_path: ./publish/functionapp.zip
